### ISSUE TITLE
Error ?

### ISSUE THREAD

**Issue by liberodark** [liberodark/steamstub#2]
```
python pyUnstub.py isaac.x64
Traceback (most recent call last):
File "pyUnstub.py", line 89, in 
main()
File "pyUnstub.py", line 86, in main
decrypt_code(header)  # собственно декрипт и перезапись кода игры
File "pyUnstub.py", line 54, in decrypt_code
section.content = util.decrypt_code(buff, header["AES_KEY"], header["AES_IV"])
TypeError: (): incompatible function arguments. The following argument types are supported:
1. (arg0: lief.Section, arg1: List[int]) -> None
```

**Comment by iOrange** [comment]
same for me
